apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
<<<<<<< HEAD
        image: avivv/ultimate-cicd:24
=======
        image: avivv/ultimate-cicd:14
>>>>>>> parent of bb99886 (Update deployment.yml)
        ports:
        - containerPort: 8080
